//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaldiUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VivaldiUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有更新已完成！ 的本地化字符串。
        /// </summary>
        internal static string text_all_updates_completed {
            get {
                return ResourceManager.GetString("text_all_updates_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的vivaldi已经是最新版！ 的本地化字符串。
        /// </summary>
        internal static string text_already_latest_message {
            get {
                return ResourceManager.GetString("text_already_latest_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已是最新版 的本地化字符串。
        /// </summary>
        internal static string text_already_latest_version {
            get {
                return ResourceManager.GetString("text_already_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string text_apply_option {
            get {
                return ResourceManager.GetString("text_apply_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string text_auto {
            get {
                return ResourceManager.GetString("text_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新Vivaldi 的本地化字符串。
        /// </summary>
        internal static string text_auto_update_vivaldi {
            get {
                return ResourceManager.GetString("text_auto_update_vivaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新Vivaldi++ 的本地化字符串。
        /// </summary>
        internal static string text_auto_update_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_auto_update_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在备份现有版本... 的本地化字符串。
        /// </summary>
        internal static string text_backing_up_existing {
            get {
                return ResourceManager.GetString("text_backing_up_existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础设置 的本地化字符串。
        /// </summary>
        internal static string text_basic_settings {
            get {
                return ResourceManager.GetString("text_basic_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string text_cancel {
            get {
                return ResourceManager.GetString("text_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查Vivaldi更新... 的本地化字符串。
        /// </summary>
        internal static string text_checking_vivaldi_update {
            get {
                return ResourceManager.GetString("text_checking_vivaldi_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查Vivaldi++更新... 的本地化字符串。
        /// </summary>
        internal static string text_checking_vpp_update {
            get {
                return ResourceManager.GetString("text_checking_vpp_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查Vivaldi++版本一致性... 的本地化字符串。
        /// </summary>
        internal static string text_checking_vpp_version_consistency {
            get {
                return ResourceManager.GetString("text_checking_vpp_version_consistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string text_chinese {
            get {
                return ResourceManager.GetString("text_chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否清理更新前创建的备份 的本地化字符串。
        /// </summary>
        internal static string text_clean_backup_after_update {
            get {
                return ResourceManager.GetString("text_clean_backup_after_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理临时文件时出现问题: {0} 的本地化字符串。
        /// </summary>
        internal static string text_cleanup_error {
            get {
                return ResourceManager.GetString("text_cleanup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string text_configure {
            get {
                return ResourceManager.GetString("text_configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在复制文件到安装目录... 的本地化字符串。
        /// </summary>
        internal static string text_copying_files {
            get {
                return ResourceManager.GetString("text_copying_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除下载的安装包 的本地化字符串。
        /// </summary>
        internal static string text_delete_installer_after_update {
            get {
                return ResourceManager.GetString("text_delete_installer_after_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        internal static string text_download_completed {
            get {
                return ResourceManager.GetString("text_download_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载vivaldi 的本地化字符串。
        /// </summary>
        internal static string text_downloading_vivaldi {
            get {
                return ResourceManager.GetString("text_downloading_vivaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载vivaldi++ 的本地化字符串。
        /// </summary>
        internal static string text_downloading_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_downloading_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用代理 的本地化字符串。
        /// </summary>
        internal static string text_enable_proxy {
            get {
                return ResourceManager.GetString("text_enable_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用vivaldi++ 的本地化字符串。
        /// </summary>
        internal static string text_enable_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_enable_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string text_english {
            get {
                return ResourceManager.GetString("text_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压安装程序... 的本地化字符串。
        /// </summary>
        internal static string text_extracting_installer {
            get {
                return ResourceManager.GetString("text_extracting_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压安装程序失败，错误代码: {0} 的本地化字符串。
        /// </summary>
        internal static string text_extraction_failed {
            get {
                return ResourceManager.GetString("text_extraction_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现已有安装文件 ({0}MB)，使用现有文件进行安装... 的本地化字符串。
        /// </summary>
        internal static string text_file_exists_using {
            get {
                return ResourceManager.GetString("text_file_exists_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现已有Vivaldi++文件 ({0}KB)，使用现有文件... 的本地化字符串。
        /// </summary>
        internal static string text_found_existing_vpp_file {
            get {
                return ResourceManager.GetString("text_found_existing_vpp_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机: 的本地化字符串。
        /// </summary>
        internal static string text_host {
            get {
                return ResourceManager.GetString("text_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        internal static string text_install {
            get {
                return ResourceManager.GetString("text_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装完成，临时文件已清理。 的本地化字符串。
        /// </summary>
        internal static string text_installation_complete_cleanup {
            get {
                return ResourceManager.GetString("text_installation_complete_cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 安装完成！ 的本地化字符串。
        /// </summary>
        internal static string text_installation_completed {
            get {
                return ResourceManager.GetString("text_installation_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装验证失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string text_installation_verification_failed {
            get {
                return ResourceManager.GetString("text_installation_verification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装到目标目录... 的本地化字符串。
        /// </summary>
        internal static string text_installing_to_directory {
            get {
                return ResourceManager.GetString("text_installing_to_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装version.dll... 的本地化字符串。
        /// </summary>
        internal static string text_installing_version_dll {
            get {
                return ResourceManager.GetString("text_installing_version_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装Vivaldi++到目标目录... 的本地化字符串。
        /// </summary>
        internal static string text_installing_vpp_to_directory {
            get {
                return ResourceManager.GetString("text_installing_vpp_to_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string text_language {
            get {
                return ResourceManager.GetString("text_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🎉已是最新版本 的本地化字符串。
        /// </summary>
        internal static string text_no_update_avaliable {
            get {
                return ResourceManager.GetString("text_no_update_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ❎未安装 的本地化字符串。
        /// </summary>
        internal static string text_not_installed {
            get {
                return ResourceManager.GetString("text_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string text_ok {
            get {
                return ResourceManager.GetString("text_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        internal static string text_password {
            get {
                return ResourceManager.GetString("text_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口: 的本地化字符串。
        /// </summary>
        internal static string text_port {
            get {
                return ResourceManager.GetString("text_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备下载Vivaldi++... 的本地化字符串。
        /// </summary>
        internal static string text_preparing_download_vpp {
            get {
                return ResourceManager.GetString("text_preparing_download_vpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备更新... 的本地化字符串。
        /// </summary>
        internal static string text_preparing_update {
            get {
                return ResourceManager.GetString("text_preparing_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理配置 的本地化字符串。
        /// </summary>
        internal static string text_proxy_config_title {
            get {
                return ResourceManager.GetString("text_proxy_config_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理设置 的本地化字符串。
        /// </summary>
        internal static string text_proxy_settings {
            get {
                return ResourceManager.GetString("text_proxy_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理类型: 的本地化字符串。
        /// </summary>
        internal static string text_proxy_type {
            get {
                return ResourceManager.GetString("text_proxy_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 💔 的本地化字符串。
        /// </summary>
        internal static string text_service_not_avaliable {
            get {
                return ResourceManager.GetString("text_service_not_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string text_update {
            get {
                return ResourceManager.GetString("text_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⬆️  的本地化字符串。
        /// </summary>
        internal static string text_update_avaliable {
            get {
                return ResourceManager.GetString("text_update_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新选项 的本地化字符串。
        /// </summary>
        internal static string text_update_settings {
            get {
                return ResourceManager.GetString("text_update_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用镜像地址 的本地化字符串。
        /// </summary>
        internal static string text_use_mirror_address {
            get {
                return ResourceManager.GetString("text_use_mirror_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        internal static string text_username {
            get {
                return ResourceManager.GetString("text_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证安装... 的本地化字符串。
        /// </summary>
        internal static string text_verifying_installation {
            get {
                return ResourceManager.GetString("text_verifying_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证Vivaldi++安装... 的本地化字符串。
        /// </summary>
        internal static string text_verifying_vpp_installation {
            get {
                return ResourceManager.GetString("text_verifying_vpp_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本一致但version.dll不存在，正在重新下载... 的本地化字符串。
        /// </summary>
        internal static string text_version_consistent_dll_missing {
            get {
                return ResourceManager.GetString("text_version_consistent_dll_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 version.dll已成功复制到安装目录。 的本地化字符串。
        /// </summary>
        internal static string text_version_dll_copied_successfully {
            get {
                return ResourceManager.GetString("text_version_dll_copied_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 version.dll复制失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string text_version_dll_copy_failed {
            get {
                return ResourceManager.GetString("text_version_dll_copy_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vivaldi浏览器 的本地化字符串。
        /// </summary>
        internal static string text_vivaldi_browser {
            get {
                return ResourceManager.GetString("text_vivaldi_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vivaldi++插件 的本地化字符串。
        /// </summary>
        internal static string text_vivaldi_plus_plugin {
            get {
                return ResourceManager.GetString("text_vivaldi_plus_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vivaldi++安装验证失败，请重试。 的本地化字符串。
        /// </summary>
        internal static string text_vpp_installation_verification_failed {
            get {
                return ResourceManager.GetString("text_vpp_installation_verification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vivaldi++已是最新版本且version.dll存在。 的本地化字符串。
        /// </summary>
        internal static string text_vpp_latest_and_dll_exists {
            get {
                return ResourceManager.GetString("text_vpp_latest_and_dll_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压Vivaldi程序 的本地化字符串。
        /// </summary>
        internal static string txt_extrating_vivaldi_installer {
            get {
                return ResourceManager.GetString("txt_extrating_vivaldi_installer", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string text_error {
            get {
                return ResourceManager.GetString("text_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请输入有效的端口号 的本地化字符串。
        /// </summary>
        internal static string text_invalid_port {
            get {
                return ResourceManager.GetString("text_invalid_port", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理已禁用，设置已保存！ 的本地化字符串。
        /// </summary>
        internal static string text_proxy_disabled_saved {
            get {
                return ResourceManager.GetString("text_proxy_disabled_saved", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存代理设置失败 的本地化字符串。
        /// </summary>
        internal static string text_proxy_save_failed {
            get {
                return ResourceManager.GetString("text_proxy_save_failed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 代理设置已保存！\n类型: {0}\n地址: {1}:{2} 的本地化字符串。
        /// </summary>
         internal static string text_proxy_settings_saved {
            get {
                return ResourceManager.GetString("text_proxy_settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string text_yes {
            get {
                return ResourceManager.GetString("text_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string text_no {
            get {
                return ResourceManager.GetString("text_no", resourceCulture);
            }
        }
    }
}
