//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivaldiUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VivaldiUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已是最新版.
        /// </summary>
        public static string text_already_latest_version {
            get {
                return ResourceManager.GetString("text_already_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        public static string text_apply_option {
            get {
                return ResourceManager.GetString("text_apply_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新Vivaldi.
        /// </summary>
        public static string text_auto_update_vivaldi {
            get {
                return ResourceManager.GetString("text_auto_update_vivaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新Vivaldi++.
        /// </summary>
        public static string text_auto_update_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_auto_update_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string text_download_completed {
            get {
                return ResourceManager.GetString("text_download_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载vivaldi.
        /// </summary>
        public static string text_downloading_vivaldi {
            get {
                return ResourceManager.GetString("text_downloading_vivaldi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载vivaldi++.
        /// </summary>
        public static string text_downloading_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_downloading_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用vivaldi++.
        /// </summary>
        public static string text_enable_vivaldi_plus {
            get {
                return ResourceManager.GetString("text_enable_vivaldi_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装.
        /// </summary>
        public static string text_install {
            get {
                return ResourceManager.GetString("text_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉.
        /// </summary>
        public static string text_no_update_avaliable {
            get {
                return ResourceManager.GetString("text_no_update_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❎.
        /// </summary>
        public static string text_not_installed {
            get {
                return ResourceManager.GetString("text_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💔.
        /// </summary>
        public static string text_service_not_avaliable {
            get {
                return ResourceManager.GetString("text_service_not_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string text_update {
            get {
                return ResourceManager.GetString("text_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬆️ .
        /// </summary>
        public static string text_update_avaliable {
            get {
                return ResourceManager.GetString("text_update_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivaldi浏览器.
        /// </summary>
        public static string text_vivaldi_browser {
            get {
                return ResourceManager.GetString("text_vivaldi_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivaldi++插件.
        /// </summary>
        public static string text_vivaldi_plus_plugin {
            get {
                return ResourceManager.GetString("text_vivaldi_plus_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压Vivaldi程序.
        /// </summary>
        public static string txt_extrating_vivaldi_installer {
            get {
                return ResourceManager.GetString("txt_extrating_vivaldi_installer", resourceCulture);
            }
        }
    }
}
